hmrc/income-tax-property-frontend

app/controllers/ExpensesLessThan1000Controller.scala, app/controllers/PropertyRentalsStartController.scala, app/forms/ExpensesLessThan1000FormProvider.scala, app/pages/ExpensesLessThan1000Page.scala, app/viewmodels/checkAnswers/ExpensesLessThan1000Summary.scala, app/views/ExpensesLessThan1000View.scala.html, app/views/PropertyRentalsStartView.scala.html, conf/app.routes, conf/messages.en, test/controllers/ExpensesLessThan1000ControllerSpec.scala, test/controllers/PropertyRentalsStartControllerSpec.scala, test/forms/ExpensesLessThan1000FormProviderSpec.scala
https://jira.tools.tax.service.gov.uk/browse/SASS-5418
This PR adds the basic scaffolded pages  for 'about property rentals' and 'expenses under £1000'
This is all generated code, apart from the updated urls and first pass adding basic content.
=> SASS-5418 basic scaffolding

app/controllers/CalculatedFigureYourselfController.scala, app/controllers/LeasePremiumPaymentController.scala, app/forms/CalculatedFigureYourselfFormProvider.scala, app/forms/LeasePremiumPaymentFormProvider.scala, app/pages/CalculatedFigureYourselfPage.scala, app/pages/LeasePremiumPaymentPage.scala, app/viewmodels/checkAnswers/CalculatedFigureYourselfSummary.scala, app/viewmodels/checkAnswers/LeasePremiumPaymentSummary.scala, app/views/CalculatedFigureYourselfView.scala.html, app/views/LeasePremiumPaymentView.scala.html, conf/app.routes, conf/messages.en, test/controllers/CalculatedFigureYourselfControllerSpec.scala, test/controllers/LeasePremiumPaymentControllerSpec.scala, test/forms/CalculatedFigureYourselfFormProviderSpec.scala, test/forms/LeasePremiumPaymentFormProviderSpec.scala
=> Initial scaffolding for change-calculated-figure-yourself and change-lease-premium-payment

app/controllers/premiumlease/LeasePremiumPaymentController.scala, app/controllers/premiumlease/PremiumsGrantLeaseController.scala, app/navigation/Navigator.scala, app/pages/premiumlease/LeasePremiumPaymentPage.scala, app/pages/premiumlease/PremiumsGrantLeasePage.scala, app/viewmodels/checkAnswers/premiumlease/LeasePremiumPaymentSummary.scala, app/viewmodels/checkAnswers/premiumlease/PremiumsGrantLeaseSummary.scala, conf/app.routes, test/controllers/premiumlease/LeasePremiumPaymentControllerSpec.scala, test/controllers/premiumlease/PremiumsGrantLeaseControllerSpec.scala, test/navigation/NavigatorSpec.scala
Also renamed one package from `premiumLease` to `premiumlease`
=> SASS-5476 add navigation

app/controllers/DeductingTaxController.scala, app/forms/DeductingTaxFormProvider.scala, app/navigation/Navigator.scala, app/pages/DeductingTaxPage.scala, app/viewmodels/checkAnswers/DeductingTaxSummary.scala, app/views/DeductingTaxView.scala.html, conf/app.routes, conf/messages.en, test/controllers/DeductingTaxControllerSpec.scala, test/forms/DeductingTaxFormProviderSpec.scala
Done
- Deducting tax page view
- Controllers
- TaxYear changes
- Yes No form validation
- Controller tests
Not done
- Amount box validation
- Income from property rentals page
=> SASS 5424 Deducting Tax from non-uk landlords

app/forms/IncomeFromPropertyRentalsFormProvider.scala, app/navigation/Navigator.scala, app/views/IncomeFromPropertyRentalsView.scala.html, test/controllers/IncomeFromPropertyRentalsControllerSpec.scala, test/navigation/NavigatorSpec.scala
Changed the navigation to go to lease premium as the pages are ready
=> SASS-5424: Fixed the navigation to go to lease premium

app/forms/premiumlease/CalculatedFigureYourselfFormProvider.scala, app/models/CalculatedFigureYourself.scala, app/pages/premiumlease/CalculatedFigureYourselfPage.scala, app/viewmodels/checkAnswers/premiumlease/CalculatedFigureYourselfSummary.scala, app/viewmodels/govuk/RadiosFluency.scala, app/views/premiumlease/CalculatedFigureYourselfView.scala.html, conf/messages.en, test/controllers/premiumlease/CalculatedFigureYourselfControllerSpec.scala, test/forms/premiumlease/CalculatedFigureYourselfFormProviderSpec.scala
This PR adds helper to handle conditional inputs within radio button questions.
=> SASS-5476 input

app/forms/DeductingTaxFormProvider.scala, app/forms/premiumlease/CalculatedFigureYourselfFormProvider.scala, app/models/CalculatedFigureYourself.scala, app/viewmodels/checkAnswers/premiumlease/CalculatedFigureYourselfSummary.scala, app/views/premiumlease/CalculatedFigureYourselfView.scala.html, conf/messages.en, test/controllers/premiumlease/CalculatedFigureYourselfControllerSpec.scala, test/forms/premiumlease/CalculatedFigureYourselfFormProviderSpec.scala
**PR changes contain the following**
£ Symbol
Field Length
Validation 
Error Messages
All the other changes were already done.
=> SASS-5476: Validation and error messages for have you calculated figure yourself page

conf/application.conf, project/plugins.sbt
=> SASS-5934: Platops PR Bot changes

app/controllers/SummaryController.scala, app/forms/RenovationAllowanceBalancingChargeFormProvider.scala, app/pages/SummaryPage.scala, app/viewmodels/summary/TaskListItem.scala, app/viewmodels/summary/TaskListTag.scala, app/views/SummaryView.scala.html, conf/messages.en, test/controllers/RenovationAllowanceBalancingChargeControllerSpec.scala, test/controllers/ResidentialFinanceCostControllerSpec.scala, test/controllers/SummaryControllerSpec.scala, test/pages/propertyrentals/SummaryPageSpec.scala
=> [SASS 5684] PIA journey: Adjustments link

app/config/FrontendAppConfig.scala, app/controllers/adjustments/PropertyIncomeAllowanceController.scala, app/controllers/propertyrentals/expenses/ExpensesStartController.scala, app/controllers/structuresbuildingallowance/AddClaimStructureBuildingAllowanceController.scala, app/controllers/structuresbuildingallowance/ClaimStructureBuildingAllowanceController.scala, app/controllers/structuresbuildingallowance/SummaryStartStructureBuildingAllowanceController.scala, app/navigation/Navigator.scala, app/pages/SummaryPage.scala, app/pages/TotalIncomePage.scala, app/viewmodels/checkAnswers/ClaimStructureBuildingAllowanceSummary.scala, app/views/ClaimStructureBuildingAllowanceView.scala.html, conf/app.routes, project/plugins.sbt, test/controllers/ClaimStructureBuildingAllowanceControllerSpec.scala, test/controllers/propertyrentals/expenses/ExpensesStartControllerSpec.scala, test/pages/propertyrentals/SummaryPageSpec.scala
Added the navigation from the summary page and reorganised the URLs
=> SASS-6413: 

app/controllers/structuresbuildingallowance/StructuredBuildingAllowanceAddressController.scala, app/forms/structurebuildingallowance/StructuredBuildingAllowanceAddressFormProvider.scala, app/views/structurebuildingallowance/StructureBuildingAllowanceView.scala.html, conf/messages.en, test/controllers/structurebuildingallowance/StructuredBuildingAllowanceAddressControllerSpec.scala, test/forms/structurebuildingallowance/StructuredBuildingAllowanceAddressFormProviderSpec.scala
…that have already been added in SBA or ESBA
=> SASS-7641 Show error when duplicate addresses

app/controllers/propertyrentals/PropertyRentalsCheckYourAnswersController.scala, test/controllers/propertyrentals/PropertyRentalsCheckYourAnswersControllerSpec.scala
Integration call for submission of data from income-tax-property frontend to the income-tax-property backend
=> SASS-8121: FE-BE Integration-Property Rentals About CYA 

conf/messages.en
Incorporated business user feedback for the User Interface captured during the Show and Tell sessions to the users
=> SASS-8912: Incorporated business user feedback 

app/controllers/rentalsandrentaroom/RentalsAndRaRCheckYourAnswersController.scala, app/controllers/session/PropertyPeriodSessionRecoveryExtensions.scala, app/controllers/ukrentaroom/CheckYourAnswersController.scala, app/controllers/ukrentaroom/ClaimExpensesOrReliefController.scala, app/forms/ukrentaroom/ClaimExpensesOrReliefFormProvider.scala, app/models/ClaimExpensesOrRelief.scala, app/models/RaRAbout.scala, app/models/RentalsAndRaRAbout.scala, app/navigation/Navigator.scala, app/pages/SummaryPage.scala, app/pages/ukrentaroom/ClaimExpensesOrRRRPage.scala, app/viewmodels/checkAnswers/ukrentaroom/ClaimExpensesOrReliefSummary.scala, app/views/ukrentaroom/ClaimExpensesOrReliefView.scala.html, conf/app.routes, conf/messages.en, test/controllers/rentalsandrentaroom/RentalsAndRaRCheckYourAnswersControllerSpec.scala, test/controllers/rentalsandrentaroom/RentalsRaRAboutCompleteControllerSpec.scala, test/controllers/session/PropertyPeriodSessionRecoveryExtensionsSpec.scala, test/controllers/ukrentaroom/AboutSectionCompleteControllerSpec.scala, test/controllers/ukrentaroom/CheckYourAnswersControllerSpec.scala, test/controllers/ukrentaroom/ClaimExpensesOrReliefControllerSpec.scala, test/controllers/ukrentaroom/adjustments/RaRAdjustmentsCYAControllerSpec.scala, test/controllers/ukrentaroom/allowances/RaRAllowancesCheckYourAnswersControllerSpec.scala, test/controllers/ukrentaroom/expenses/ExpensesCheckYourAnswersRRControllerSpec.scala, test/controllers/ukrentaroom/expenses/UkRentARoomExpensesIntroControllerSpec.scala, test/forms/ukrentaroom/ClaimExpensesOrReliefFormProviderSpec.scala, test/models/RaRAboutSpec.scala, test/navigation/NavigatorSpec.scala, test/pages/propertyrentals/SummaryPageSpec.scala
Organised the routes as per the UI flow
=> SASS-9049: Fixed rent-a-room URLs, renamed few controllers 

app/controllers/ukrentaroom/ClaimExpensesOrReliefController.scala, app/forms/ukrentaroom/ClaimExpensesOrReliefFormProvider.scala, conf/messages.cy, conf/messages.en, test/controllers/ukrentaroom/ClaimExpensesOrReliefControllerSpec.scala, test/forms/behaviours/CurrencyFieldBehaviours.scala, test/forms/ukrentaroom/ClaimExpensesOrReliefFormProviderSpec.scala
=> SASS-9004 | Add error message to claim expenses or rent  room relief page

app/pages/rentalsandrentaroom/allowances/RentalsRaRAllowancesCompletePage.scala
It was coming under Expenses journey instead of Allowances journey
=> SASS-8962: Adding the fix for isRentalsRaRAllowanceComplete.

app/controllers/SummaryController.scala, app/controllers/foreign/ForeignSelectCountriesCompleteController.scala, app/controllers/foreign/ForeignTaxSectionCompleteController.scala, app/controllers/session/PropertyPeriodSessionRecoveryExtensions.scala, app/models/FetchedBackendData.scala, app/models/propertyrentals/income/Income.scala, app/models/propertyrentals/income/SaveIncome.scala, app/navigation/ForeignPropertyNavigator.scala, app/pages/PageConstants.scala, app/pages/enhancedstructuresbuildingallowance/ClaimEsbaPage.scala, app/pages/foreign/AddCountriesRentedPage.scala, app/pages/foreign/ClaimPropertyIncomeAllowanceOrExpensesPage.scala, app/pages/foreign/ForeignPropertySummaryPage.scala, app/pages/foreign/ForeignSelectCountriesCompletePage.scala, app/pages/foreign/ForeignTaxSectionCompletePage.scala, app/pages/foreign/PropertyIncomeReportPage.scala, app/pages/propertyrentals/expenses/ExpensesSectionFinishedPage.scala, app/views/SummaryView.scala.html, test/controllers/SummaryControllerSpec.scala, test/controllers/foreign/ForeignPremiumsGrantLeaseControllerSpec.scala, test/controllers/foreign/ForeignSelectCountriesCompleteControllerSpec.scala, test/controllers/foreign/ForeignTaxSectionCompleteControllerSpec.scala, test/controllers/ukrentaroom/adjustments/RaRAdjustmentsCompleteControllerSpec.scala, test/forms/rentalsandrentaroom/adjustments/BusinessPremisesRelocationAllowanceBalancingChargeFormProviderSpec.scala
=> SASS-10412: Normalising the fields for the frontend sections to be stored to allow easy retrieval

app/controllers/foreign/ClaimForeignTaxCreditReliefController.scala, app/controllers/foreign/ForeignTaxCheckYourAnswersController.scala, app/controllers/foreign/ForeignTaxSectionCompleteController.scala, app/controllers/foreign/ForeignYearLeaseAmountController.scala, app/controllers/foreign/income/ForeignPropertyIncomeStartController.scala, app/navigation/ForeignPropertyNavigator.scala, app/navigation/Navigator.scala, app/pages/foreign/ForeignPropertySummaryPage.scala, app/views/ForeignPropertyDetailsView.scala.html, app/views/SummaryView.scala.html, app/views/foreign/income/ForeignPropertyIncomeStartView.scala.html, conf/foreign.routes, conf/messages.cy, conf/messages.en, test/controllers/foreign/ClaimForeignTaxCreditReliefControllerSpec.scala, test/controllers/foreign/ForeignIncomeTaxControllerSpec.scala, test/controllers/foreign/ForeignPremiumsGrantLeaseControllerSpec.scala, test/controllers/foreign/ForeignReceivedGrantLeaseAmountControllerSpec.scala, test/controllers/foreign/ForeignTaxCheckYourAnswersControllerSpec.scala, test/controllers/foreign/ForeignTaxSectionCompleteControllerSpec.scala, test/controllers/foreign/ForeignYearLeaseAmountControllerSpec.scala, test/controllers/foreign/income/ForeignPropertyIncomeStartControllerSpec.scala
Tested with NINO: AC190000B, MTDITID: XGIT00001016274
Amended Foreign Tax controllers to use ForeignPropertyNavigator
=> SASS-9624 - added foreign property income hyperlink and start page

app/controllers/about/AboutPropertyCompleteController.scala, app/controllers/adjustments/PropertyIncomeAllowanceController.scala, app/controllers/foreign/ForeignSelectCountriesCompleteController.scala, app/controllers/foreign/ForeignTaxSectionCompleteController.scala, app/controllers/propertyrentals/AboutPropertyRentalsSectionFinishedController.scala, app/controllers/propertyrentals/expenses/ExpensesStartController.scala, app/controllers/rentalsandrentaroom/income/RentalsAndRentARoomIncomeStartController.scala, app/controllers/ukrentaroom/expenses/UkRentARoomExpensesIntroController.scala, app/navigation/ForeignPropertyNavigator.scala, app/pages/SummaryPage.scala, conf/foreign.routes, test/controllers/ExpensesRRSectionCompleteControllerSpec.scala, test/controllers/adjustments/RentalsAdjustmentsCompleteControllerSpec.scala, test/controllers/foreign/ForeignSelectCountriesCompleteControllerSpec.scala, test/controllers/foreign/ForeignTaxCheckYourAnswersControllerSpec.scala, test/controllers/propertyrentals/expenses/ExpensesSectionFinishedControllerSpec.scala, test/controllers/rentalsandrentaroom/RentalsRaRAboutCompleteControllerSpec.scala, test/controllers/rentalsandrentaroom/income/RentalsRaRIncomeCompleteControllerSpec.scala, test/controllers/ukrentaroom/AboutSectionCompleteControllerSpec.scala, test/controllers/ukrentaroom/allowances/RaRAllowancesCompleteControllerSpec.scala, test/forms/foreign/ClaimPropertyIncomeAllowanceOrExpensesFormProviderSpec.scala, test/navigation/FakeForeignPropertyNavigator.scala, test/service/CYADiversionServiceSpec.scala
Removed some redundant imports
=> SASS-10412: Refactored the routes to align with the journey for select-country 

app/controllers/foreign/CalculatedPremiumLeaseTaxableController.scala, app/controllers/foreign/ForeignTaxCheckYourAnswersController.scala, app/controllers/foreign/ForeignTaxSectionCompleteController.scala, app/controllers/session/PropertyPeriodSessionRecoveryExtensions.scala, app/forms/ForeignTaxSectionCompleteFormProvider.scala, app/forms/foreign/ForeignIncomeTaxFormProvider.scala, app/models/ForeignIncomeTax.scala, app/navigation/ForeignPropertyNavigator.scala, app/pages/foreign/ForeignPropertySummaryPage.scala, app/pages/foreign/ForeignTaxSectionCompletePage.scala, app/viewmodels/checkAnswers/foreign/CalculatedPremiumLeaseTaxableSummary.scala, app/viewmodels/checkAnswers/foreign/ForeignOtherIncomeFromPropertySummary.scala, app/views/foreign/ForeignIncomeTaxView.scala.html, app/views/foreign/ForeignTaxSectionCompleteView.scala.html, conf/foreign.routes, test/controllers/foreign/ForeignIncomeTaxControllerSpec.scala, test/controllers/foreign/ForeignTaxCheckYourAnswersControllerSpec.scala, test/controllers/foreign/ForeignTaxSectionCompleteControllerSpec.scala, test/forms/foreign/ForeignIncomeTaxFormProviderSpec.scala, test/forms/foreign/ForeignTaxSectionCompleteFormProviderSpec.scala
The UI should now update the status for ForeignTax
=> SASS-10437: Foreign Property - Implement navigation functionality for 'Foreign tax' journey

app/controllers/foreign/structuresbuildingallowance/ForeignStructuresBuildingAllowanceAddressController.scala, app/forms/foreign/structurebuildingallowance/ForeignStructuresBuildingAllowanceAddressFormProvider.scala, app/forms/mappings/Constraints.scala, app/models/ForeignAddressable.scala, app/models/ForeignStructuresBuildingAllowanceAddress.scala, app/pages/foreign/structurebuildingallowance/ForeignStructuresBuildingAllowanceAddressPage.scala, app/viewmodels/checkAnswers/ForeignStructuresBuildingAllowanceAddressSummary.scala, app/views/foreign/structurebuildingallowance/ForeignStructuresBuildingAllowanceAddressView.scala.html, conf/foreign.routes, conf/messages.cy, conf/messages.en, test/controllers/foreign/structurebuildingallowance/ForeignStructuresBuildingAllowanceAddressControllerSpec.scala, test/forms/foreign/structurebuildingallowance/ForeignStructuresBuildingAllowanceAddressFormProviderSpec.scala
=> SASS-9743: Foreign Property - SBA section: Create 'Structure and building allowance address' page

app/controllers/foreign/allowances/ForeignOtherCapitalAllowancesController.scala, app/controllers/foreign/allowances/ForeignPropertyAllowancesStartController.scala, app/controllers/foreign/allowances/ForeignReplacementOfDomesticGoodsController.scala, app/controllers/foreign/allowances/ForeignZeroEmissionCarAllowanceController.scala, app/controllers/foreign/allowances/ForeignZeroEmissionGoodsVehiclesController.scala, app/navigation/ForeignPropertyNavigator.scala, app/views/foreign/allowances/ForeignPropertyAllowancesStartView.scala.html, conf/foreign.routes, test/navigation/foreign/ForeignPropertyNavigatorSpec.scala
This is a pre requisite to build CYA Page
=> SASS-10525: Implement navigation functionality for 'Allowances' journey

app/audit/ForeignPropertyAllowances.scala, app/controllers/foreign/allowances/ForeignAllowancesCheckYourAnswersController.scala, app/controllers/foreign/allowances/ForeignCapitalAllowancesForACarController.scala, app/navigation/ForeignPropertyNavigator.scala, app/pages/foreign/allowances/ForeignCapitalAllowancesForACarPage.scala, app/views/foreign/allowances/ForeignPropertyAllowancesStartView.scala.html, test/controllers/foreign/allowances/ForeignAllowancesCheckYourAnswersControllerSpec.scala
=> Foreign Property - Logic missing for Allowances journey when using cash-basis accounting
